# Use root/example as user/password credentials
version: "3.1"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-perguntai
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
